Repository jenkinsci/datadog-plugin, pull requests merged in 2020-08, with the labels that each got.

#107 Update changelog for 1.2.0 release
  CHANGELOG.md
Labels: documentation

#108 Use 1.x README
  README.md
Labels: documentation

#110 Preparing release 2.0.0
  CHANGELOG.md
  README.md
Labels: documentation

#96 APM Traces for Jenkins Build/Pipelines
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ClientFactory.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/BuildSpanAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/BuildSpanManager.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/BuildTextMapAdapter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/StepDataManager.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogUtilitiesTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTestWrapper.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracesUtilities.java
Labels: changelog/Added, documentation

#101 Add job name tag to pipelines in queues
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisher.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePipelinePublisherTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/publishers/testPipeline.txt
Labels: changelog/Added

#112 Changelog 2.1.0
  CHANGELOG.md
Labels: documentation

#114 Prevent exception if traces form data is not present.
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
Labels: changelog/Fixed, kind/bug, severity/major

#115 Fix NPE when traces collection is disabled
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
Labels: changelog/Fixed, kind/bug, severity/major

#116 Changelog v2.1.1
  CHANGELOG.md
Labels: documentation
