Repository jenkinsci/datadog-plugin, pull requests merged in 2020-01, with the labels that each got.

#11 Update CODEOWNERS
  .github/CODEOWNERS
Labels: changelog/no-changelog

#14 Documentation update
  README.md
Labels: changelog/no-changelog, documentation

#12 add jenkinsfile and fix spotbugs issues
  .azure-pipelines/all.yml
  Jenkinsfile
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ConcurrentMetricCounters.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ConfigChangedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/UserAuthenticationEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/SuppressFBWarnings.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/TagsUtil.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildAbortedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildFinishedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildStartedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ComputerLaunchFailedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ComputerOfflineEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ComputerOnlineEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ConfigChangedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ItemCRUDEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ItemCopiedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ItemLocationChangedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/SCMCheckoutCompletedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/UserAuthenticationEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTestWrapper.java
  src/test/java/org/datadog/jenkins/plugins/datadog/stubs/BuildStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/stubs/ProjectStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/stubs/QueueStub.java
Labels: changelog/no-changelog, dev/tooling

#17 Bug fix when calling fetching build tags from job properties
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ClientFactory.java
Labels: changelog/Fixed, kind/bug, severity/major

#18 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: changelog/no-changelog, documentation

#20 Prepare 1.0.1 release
  CHANGELOG.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: documentation

#23 Update links
  README.md
Labels: changelog/no-changelog, documentation

#24 Exception Logging improvements
  settings.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogJobProperty.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogComputerListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogItemListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSaveableListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSecurityListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogCountersPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogJenkinsPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisher.java
Labels: changelog/Added

#27 Typo fix
  README.md
Labels: changelog/no-changelog, documentation

#28 Update Doc
  DEVELOPMENT.md
  README.md
  RELEASING.md
Labels: changelog/no-changelog, documentation

#30 Fix missing tags when submitting service checks
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
Labels: changelog/Fixed, kind/bug, severity/critical

#31 Add back changelogs instructions
  RELEASING.md
Labels: changelog/no-changelog, documentation

#33 Update RELEASING.md
  RELEASING.md
Labels: changelog/no-changelog, documentation

#34 Add 3rd party licenses
  LICENSE-3rdparty.csv
Labels: changelog/no-changelog

#35 Prepare 1.0.2 release
  CHANGELOG.md
  pom.xml
Labels: changelog/no-changelog, documentation

#36 Fix release prep
  pom.xml
Labels: changelog/no-changelog, dev/tooling

#37 revert release
  pom.xml
Labels: changelog/no-changelog, dev/tooling
