Repository jenkinsci/datadog-plugin, pull requests merged in 2020-09, with the labels that each got.

#118 Added tests when trace collection is disabled
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#120 Update dd-trace-java to version 0.61.0
  pom.xml
Labels: changelog/no-changelog

#119 Fixes for Jenkins pipelines traces tags
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Fixed

#117 User-defined service name for traces collection
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ClientFactory.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#121 Add traceID and spanID to every log line.
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
Labels: changelog/Added

#123 Fix the recover of correct StepData info associated with a Step
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/StepDataAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/StepDataManager.java
Labels: changelog/Fixed

#124 Adapt job name for APM traces
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/JobNameWrapper.java
  src/test/java/org/datadog/jenkins/plugins/datadog/traces/JobNameWrapperTest.java
Labels: changelog/Fixed

#125 Fix hostname resolution for APM traces in pipeline nodes
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
Labels: changelog/Fixed

#127 Add queue_time metric in APM traces as tag
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/TimeInQueueAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
Labels: changelog/Added

#128 Fix missing logs attached to the APM trace
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/logs/LogCollectionTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptionsTest.java
Labels: changelog/Fixed

#129 Force Sampling Priority to SAMPLER_KEEP
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/no-changelog

#130 Changelog v2.2.0
  CHANGELOG.md
Labels: documentation

#132 Change 'CANCELLED' to 'CANCELED' as build result tag. (US spelling)
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
Labels: changelog/Fixed

#131 Update readme to include jenkins hostname field
  README.md
Labels: changelog/no-changelog, documentation
