Repository jenkinsci/datadog-plugin, pull requests merged in 2020-07, with the labels that each got.

#90 Don't fail validation if log collection is not working
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/Fixed

#91 Update CI to test more versions
  Jenkinsfile
Labels: changelog/no-changelog

#93 Use more inclusive naming of config
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/logs/LogCollectionTest.java
Labels: documentation

#94 Use inclusive naming
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
Labels: changelog/Added, documentation

#95 Keep backwards compatibility with old config naming
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Fixed

#97 Update changelog for 1.2.0 release
  CHANGELOG.md
Labels: documentation

#98 Update changelog for 1.2.0 release (#97)
  CHANGELOG.md
Labels: documentation

#88 Add a Datadog build step
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogTaskListenerDecorator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptions.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/DatadogPipelineAction.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/steps/DatadogOptions/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptionsTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/steps/logCollectedInOptions.txt
  src/test/resources/org/datadog/jenkins/plugins/datadog/steps/pipelineMetricTags.txt
Labels: changelog/Added

#100 Fix javadoc
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
Labels: changelog/no-changelog

#84 Add queue test to ensure metric consistency
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisherTest.java
Labels: changelog/no-changelog

#92 Add result tag to stage metrics
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineDefinition.txt
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineSuccess.txt
Labels: changelog/Fixed, documentation

#102 Add dashboard screenshot to readme
  README.md
  images/dashboard.png
Labels: documentation

#103 Remove the result tag from the service check
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
Labels: documentation

#106 Remove the result tag from the service check (#103)
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
Labels: documentation
