Repository jenkinsci/datadog-plugin, pull requests merged in 2020-12, with the labels that each got.

#160 Fix stage.name propagation for all children jobs in Jenkins Pipelines
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineStages.txt
Labels: changelog/Fixed

#163 Prepare release 2.5.0
  CHANGELOG.md
Labels: documentation

#164 Add ci.status for Jenkins Build/Pipelines
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#159 Add ci.queue_time for pipeline/stage/job traces
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogQueueListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/FlowNodeQueueData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineQueueInfoAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/TimeInQueueAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineQueueOnPipeline.txt
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineQueueOnStages.txt
Labels: changelog/Added

#165 Add _dd.ci.level tag to Jenkins Build/Pipelines
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added
