Repository jenkinsci/datadog-plugin, pull requests merged in 2020-06, with the labels that each got.

#64 DOCS-946 Global customization
  README.md
Labels: changelog/no-changelog

#66 [DOCS-925] add custom log source step to install instructions
  README.md
Labels: changelog/no-changelog, documentation

#67 Add minimum jenkins version
  README.md
  pom.xml
Labels: changelog/Added, documentation

#69 Update changelog for 1.1.2 release
  CHANGELOG.md
Labels: documentation

#72 Add workflow-job dependency
  README.md
  pom.xml
Labels: documentation

#70 Update development docs
  DEVELOPMENT.md
  RELEASING.md
Labels: documentation

#61 Enforce POST in form validation
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Fixed

#71 Add new node status metrics
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisher.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogMetric.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisherTest.java
Labels: changelog/Added, documentation

#76 Collect and submit jenkins.job.stage_duration
  README.md
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineDefinition.txt
Labels: changelog/Added, documentation

#78 Update readme with correct version and logs section
  README.md
Labels: changelog/no-changelog, documentation

#79 Fix flakey test
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisherTest.java
Labels: changelog/no-changelog

#77 Add pipeline pause and build duration
  README.md
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerTestWrapper.java
  src/test/java/org/datadog/jenkins/plugins/datadog/stubs/RunExtStub.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: changelog/Added, documentation

#73 Add new queue metrics with job tags
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisher.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisherTest.java
Labels: changelog/Added, documentation

#80 Update pom for 1.x
  README.md
  pom.xml
Labels: changelog/Fixed, documentation

#81 Update failedlastValidation if client passes validation
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/Fixed
