Repository jenkinsci/datadog-plugin, pull requests merged in 2020-10, with the labels that each got.

#134 Expose trace IDs as environment variables
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/GeneratedSpanIdAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/TraceStepEnvironmentContributor.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#135 Add commit message, author, and committer info to traces
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/GitCommitAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RevCommitRepositoryCallback.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/git/gitFolder.zip
Labels: changelog/Added

#136 Git commit related information only in root span.
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/no-changelog

#139 Add _dd.ci.build_level tag for traces
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/no-changelog

#141 Remove build_type from internal spans
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/no-changelog

#143 Changelog for v2.3.0
  CHANGELOG.md
Labels: documentation

#144 Fix timezone assertions
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/no-changelog

#145 fr-142 support jenkins.job.stage_completed
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added, community, documentation

#148 Update changelog for 2.4.0 release
  CHANGELOG.md
Labels: documentation

#149 Propagate CI parents tags in Jenkins Pipelines traces
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#150 Add git.default_branch tag to Jenkins Build/Pipeline traces
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/GitRepositoryAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RepositoryInfo.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RepositoryInfoCallback.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#151 Configure hostname in the tracer
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/Fixed

#152 Add dec and hex flavour to the environment variable trace IDs.
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/TraceStepEnvironmentContributor.java
Labels: changelog/Changed
