Repository jenkinsci/datadog-plugin, pull requests merged in 2021-12, with the labels that each got.

#261 Update changelog with 3.4.0 release
  CHANGELOG.md
Labels: documentation

#262 Revert 3.4.0 release updates
  CHANGELOG.md
  pom.xml
Labels: documentation

#263 Fix javadoc errors in all files
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
Labels: changelog/no-changelog

#264 Update changelog for 3.4.0
  CHANGELOG.md
Labels: documentation

#242 Accept "0" as a valid port value to support UDS
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
Labels: stale

#267 Add javadoc step to test phase
  CONTRIBUTING.md
  pom.xml
Labels: documentation
