Repository jenkinsci/datadog-plugin, pull requests merged in 2021-03, with the labels that each got.

#177 Add dev troubleshooting comment
  DEVELOPMENT.md
Labels: documentation, stale

#189 Update documentation anchor links and formatting
  README.md
Labels: changelog/no-changelog, documentation

#192 Add documentation for agent configuration
  DEVELOPMENT.md
Labels: changelog/no-changelog, documentation

#191 Add stage_pause_duration metric
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineDefinition.txt
Labels: changelog/Added, documentation

#187 Always include purposefully-written messages for severe error cases
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogJobProperty.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogComputerListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogItemListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSaveableListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSecurityListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogConsoleLogFilter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogWriter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogCountersPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogJenkinsPublisher.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePublisher.java
Labels: changelog/Added

#190 Support environment variables in global tags and global job tags
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-globalJobTagsEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-globalTagsEntry.html
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalTagsTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogEventStub.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/testPipeline.txt
Labels: changelog/Added, documentation

#194 Prepare Changelog for 2.9.0
  CHANGELOG.md
Labels: documentation

#195 Fix grammar in docs
  DEVELOPMENT.md
Labels: changelog/no-changelog, documentation

#196 Remove the exposure of traceIDs as environment variables
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/GeneratedSpanIdAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/TraceStepEnvironmentContributor.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Removed

#197 Changelog 2.10.0
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
