Repository jenkinsci/datadog-plugin, pull requests merged in 2021-09, with the labels that each got.

#241 Fix stage breakdown to json conversion
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StageData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/StageDataTest.java
Labels: changelog/Fixed, kind/bug, severity/normal

#243 Fix ConcurrentModificationException when serializing `StepDataAction`
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/StepDataAction.java
Labels: changelog/Fixed

#244 Prepare 3.1.2
  CHANGELOG.md
Labels: documentation

#240 Reduce the `GitClient` instances creation for CI Visibility pipelines
  src/main/java/org/datadog/jenkins/plugins/datadog/audit/DatadogAudit.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/GitRepositoryAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RepositoryInfo.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RepositoryInfoCallback.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtilsTest.java
Labels: changelog/Fixed

#245 Prepare 3.1.3
  CHANGELOG.md
Labels: documentation

#246 Propagate trace/span IDs via environment variables for Jenkins Pipelines
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepTraceData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/StepTraceDataAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/TraceStepEnvironmentContributor.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/TracerConstants.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/message/TraceSpan.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogTraceAbstractTest.java
Labels: changelog/Added

#248 Prepare 3.2.0
  CHANGELOG.md
Labels: documentation

#250 Prepare 3.2.0 v2
  CHANGELOG.md
Labels: documentation
