Repository jenkinsci/datadog-plugin, pull requests merged in 2021-06, with the labels that each got.

#213 Propagate error tags to all node parents for Jenkins Pipelines traces
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineErrorOnStages.txt
Labels: changelog/Added

#212 Add node labels to Jenkins Pipelines traces
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineNodeInfoAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/CITags.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogUtilitiesTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#214 Add best-effort strategy to find the valid Git commit in Jenkins Pipelines traces.
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtilsTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelinesOverrideGitCommit.txt
Labels: changelog/Added

#216 Prepare 2.13.0
  CHANGELOG.md
Labels: documentation

#217 DOCS-2031 Lint headings
  README.md
Labels: changelog/no-changelog

#219 Lower log severity
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
Labels: changelog/Fixed

#220 Add note on pipeline tag limitation
  README.md
Labels: documentation

#221 Enable CI Visibility UI
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ClientFactory.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-globalJobTagsEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-globalTagsEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-targetHostEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-targetLogCollectionPortEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-targetPortEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-targetTraceCollectionPortEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-traceServiceNameEntry.html
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/logs/LogCollectionTest.java
Labels: changelog/Added, documentation

#222 Prepare release 3.0.0
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#223 Reinitialize Datadog Client when tracer collection port is updated.
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/Fixed

#224 Prepare v3.0.0 v2
  CHANGELOG.md
Labels: documentation

#225 Fix version to snapshot
  pom.xml
Labels: changelog/no-changelog

#226 Complete javadoc
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/GitInfoUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
Labels: changelog/no-changelog
