Repository jenkinsci/datadog-plugin, pull requests merged in 2021-01, with the labels that each got.

#168 Configure the default branch using environment variable
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
Labels: changelog/Added

#169 Prepare release 2.7.0
  CHANGELOG.md
Labels: documentation

#172 Update dd-trace-java version to 0.71.0
  pom.xml
Labels: changelog/Added

#171 Avoid using Gson instance in Datadog Traces
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StageData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/json/JsonUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/json/ToJson.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/StageDataTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/util/json/JsonUtilsTest.java
Labels: changelog/Fixed

#174 Fix function name
  README.md
Labels: changelog/no-changelog

#173 Avoid dropping spans in Jenkins Build/Pipelines traces
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DogStatsDClient.java
Labels: changelog/Fixed

#175 Prepare release 2.8.0
  CHANGELOG.md
Labels: documentation
