Repository jenkinsci/datadog-plugin, pull requests merged in 2022-02, with the labels that each got.

#276 Add option to refresh statsd client when the host's IP has changed
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Added

#275 Update docs to fix anchor link
  README.md
Labels: changelog/no-changelog

#277 Add changelog for 3.5.0
  CHANGELOG.md
Labels: documentation
