Repository jenkinsci/datadog-plugin, pull requests merged in 2022-01, with the labels that each got.

#268 Properly validate credentials API key before using
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
Labels: changelog/Fixed

#270 Ban vulnerable log4j versions
  pom.xml
Labels: changelog/Fixed

#271 Update changelog for 3.4.1
  CHANGELOG.md
Labels: documentation

#273 Revert javadoc step
  CONTRIBUTING.md
  pom.xml
Labels: changelog/no-changelog, documentation

#274 Update button text to be more clear
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Fixed
