Repository jenkinsci/datadog-plugin, pull requests merged in 2022-10, with the labels that each got.

#313 Add option to not cache build run when calculating pause duration
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Added

#309 CI Visibility support in Agentless mode
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/ClientFactory.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/BuildWebhookAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogBaseBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogBasePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookPipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientTest.java
Labels: documentation

#314 Add changelog for 5.1.0-beta-1 release
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
