Repository jenkinsci/datadog-plugin, pull requests merged in 2022-04, with the labels that each got.

#286 Fix ConcurrentModificationException when serializing `PipelineQueueInfoAction`
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogQueueListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineQueueInfoAction.java
Labels: changelog/Fixed

#287 Use `jnr-posix-api` plugin
  Jenkinsfile
  README.md
  pom.xml
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
Labels: changelog/Changed, documentation

#289 Use the correct payload buffer to send data for CI Visibility
  src/main/java/org/datadog/jenkins/plugins/datadog/transport/NonBlockingHttpClient.java
Labels: changelog/Fixed

#291 [3.x][Test Fix] Disconnecting worker when the test finishes
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
Labels: changelog/no-changelog

#292 [3.x] Use the correct payload buffer to send data for CI Visibility
  src/main/java/org/datadog/jenkins/plugins/datadog/transport/NonBlockingHttpClient.java
Labels: changelog/Fixed

#293 CHANGELOG 3.5.2
  CHANGELOG.md
Labels: documentation

#290 Prepare CHANGELOG 4.0.0
  CHANGELOG.md
Labels: documentation

#294 Fix date in changelog
  CHANGELOG.md
Labels: documentation
