Repository jenkinsci/datadog-plugin, pull requests merged in 2022-08, with the labels that each got.

#298 [CI Visibility] Add hostname info for events executed in Jenkins workers.
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipeline.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildPipelineNode.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineNodeInfoAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/StepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineOnWorkers.txt
Labels: changelog/Added

#300 CHANGELOG 4.1.0-beta-1
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#296 make the plugin see data stream last by adjusting decorator order, to avoid logging unmasked data
  Jenkinsfile
  README.md
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogTaskListenerDecorator.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogTraceAbstractTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisherTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogQueuePipelinePublisherTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineDefinition.txt
Labels: changelog/Changed

#301 Change tested version in CI
  Jenkinsfile
Labels: changelog/no-changelog

#302 Attach byte buddy agent to jvm when running tests
  pom.xml
Labels: changelog/no-changelog

#303 Remove unneeded log4j exclusion
  pom.xml
Labels: changelog/no-changelog

#304 Add changelog for 5.0.0
  CHANGELOG.md
Labels: documentation
