Repository jenkinsci/datadog-plugin, pull requests merged in 2023-11, with the labels that each got.

#364 Add ability to granualarly filter events
  .gitignore
  README.md
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/AbstractDatadogSimpleEvent.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/BuildAbortedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/BuildFinishedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/BuildStartedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ComputerLaunchFailedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ComputerOfflineEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ComputerOnlineEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ConfigChangedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ItemCRUDEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ItemCopiedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/ItemLocationChangedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/SCMCheckoutCompletedEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/events/UserAuthenticationEventImpl.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogComputerListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogItemListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSaveableListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSecurityListener.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfigurationTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogEventStub.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/ConfigChangedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/UserAuthenticationEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogFilteringEventsTest.java
Labels: documentation

#368 Add fallback logic for job name and build tag in build data
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/BuildDataTest.java
Labels: changelog/Fixed

#369 Add changelog for 5.6.0
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#370 Fix javadoc errors
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/GitInfoUtils.java
Labels: changelog/no-changelog

#373 Add emitConfigChangeEvents option back
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfigurationTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/test-config.yml
Labels: changelog/Fixed

#374 Update changelog for 5.6.1
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
