Repository jenkinsci/datadog-plugin, pull requests merged in 2023-08, with the labels that each got.

#351 Add changelog for 5.4.2
  CHANGELOG.md
Labels: documentation

#355 Add changelog for 5.5.0 release
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#358 Revert failed release
  pom.xml
Labels: changelog/no-changelog

#359 Update changelog date
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#356 When creating a new BuildData instance, use BuildData populated during previous pipeline stages
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
Labels: changelog/Fixed

#360 Use new http client in getAwsInstanceID method
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
Labels: changelog/Fixed

#347 Fix file descriptor leak in logger reinitialisation logic and print stack trace in severe logs
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
Labels: changelog/Fixed
