Repository jenkinsci/datadog-plugin, pull requests merged in 2024-06, with the labels that each got.

#430 Short-circuit StageData creation in trace generation
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogBaseBuildLogic.java
Labels: changelog/Fixed

#431 Prepare CHANGELOG 7.1.0
  CHANGELOG.md
Labels: documentation

#433 Update APM auto-instrumentation to match any Java process
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/JavaConfigurator.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/help-languages.html
Labels: changelog/Fixed

#432 Consider job inclusion/exclusion setting when tracking logs
  README.md
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogConsoleLogFilter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogTaskListenerDecorator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptions.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-blacklistEntry.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-whitelistEntry.html
  src/test/java/org/datadog/jenkins/plugins/datadog/logs/DatadogConsoleLogFilterTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/logs/DatadogTaskListenerDecoratorTest.java
Labels: changelog/Fixed, documentation

#435 added extra conditions for counting executors
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisher.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogComputerPublisherTest.java
Labels: changelog/Fixed
