Repository jenkinsci/datadog-plugin, pull requests merged in 2024-12, with the labels that each got.

#475 Propagate executor number data from step trace to stage trace and pipeline trace
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineNodeInfoAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineStepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/node/NodeInfoAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTraceBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookBuildLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookPipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/PipelineNodeInfoActionConverterTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/node/NodeInfoActionConverterTest.java
Labels: changelog/Fixed

#473 Enable traces batching by default
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogApiClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/write/TraceWriteStrategy.java
Labels: changelog/Added

#474 Fix auto-instrumentation to inject tracer into Gradle Launcher instead of Gradle Daemon
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/JavaConfigurator.java
Labels: changelog/Fixed

#468 Fix Datadog pipeline options scope
  README.md
  docker/controller-node/50-create-jobs.groovy
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerEnvironmentContributor.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerStepEnvironmentContributor.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DotnetConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/JavaConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/JavascriptConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/PythonConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/TracerConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineStepData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptions.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/DatadogPipelineAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/steps/TestOptimization.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookPipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/TagsUtil.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/config.jelly
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/help-languages.html
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/help-on.html
  src/test/java/org/datadog/jenkins/plugins/datadog/apm/TracerInjectionIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/util/TagsUtilTest.java
  src/test/resources/org/datadog/jenkins/plugins/datadog/apm/test-multistage-maven-pipeline-with-datadog-step.txt
  src/test/resources/org/datadog/jenkins/plugins/datadog/listeners/testPipelineStageTags.txt
Labels: changelog/Fixed, documentation

#477 Prepare CHANGELOG 8.3.0
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#476 Implement automatic Test Optimization instrumentation for Ruby projects
  README.md
  docker/agent-node/Dockerfile-ruby
  docker/controller-node/jobs/test-pipeline-ruby.cps
  docker/docker-compose.yaml
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/RubyConfigurator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/Semver.java
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/TracerLanguage.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/help-languages.html
  src/test/java/org/datadog/jenkins/plugins/datadog/apm/SemverTest.java
Labels: changelog/Added

#478 Do not compress traces and logs batches when sending to old EVP proxy
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/BatchSender.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogApiClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/write/AgentTraceWriteStrategy.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/BatchSenderTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientTest.java
Labels: changelog/Fixed

#479 Do not compress traces and logs batches when sending to old EVP proxy
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/BatchSender.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogApiClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/write/AgentTraceWriteStrategy.java
  src/test/java/org/datadog/jenkins/plugins/datadog/clients/BatchSenderTest.java
Labels: changelog/Fixed

#480 Release 8.3.1 CHANGELOG
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#481 Release 8.3.1 CHANGELOG
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
