Repository jenkinsci/datadog-plugin, pull requests merged in 2024-11, with the labels that each got.

#465 Only instrument Maven/Gradle/SBT/Ant when doing tests auto-instrumentation
  src/main/java/org/datadog/jenkins/plugins/datadog/apm/JavaConfigurator.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/apm/DatadogTracerJobProperty/help-languages.html
Labels: changelog/Fixed

#453 Add jenkins.plugin.withWarning metric
  README.md
  pom.xml
  src/main/java/org/datadog/jenkins/plugins/datadog/model/PluginData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogJenkinsPublisher.java
  src/test/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogJenkinsPublisherTest.java
Labels: changelog/Added, documentation

#466 Update changelog for 8.1.0 release
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#470 docs(CHANGELOG) Inform user about the deprecated `retryLogs` JCasC attribute
  CHANGELOG.md
Labels: documentation

#472 Update changelog for 8.2.0 release
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
