Repository jenkinsci/datadog-plugin, pull requests merged in 2025-01, with the labels that each got.

#482 Do not use commit SHA as branch name
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/GitInfoUtils.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/RepositoryInfoCallback.java
Labels: changelog/Fixed

#483 Do not tag traces with shared libraries Git metadata
  docker/controller-node/70-configure-shared-library.groovy
  docker/controller-node/Dockerfile
  docker/controller-node/jobs/test-pipeline-shared-library.cps
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
Labels: changelog/Fixed

#486 Add a guard check against stack overflow when initializing BuildData
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogStepListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogConsoleLogFilter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogTaskListenerDecorator.java
  src/main/java/org/datadog/jenkins/plugins/datadog/logs/DatadogWriter.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogTracePipelineLogic.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookPipelineLogic.java
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalTagsTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildAbortedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildFinishedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildStartedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/events/SCMCheckoutCompletedEventTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/model/BuildDataTest.java
Labels: changelog/Fixed

#487 Update changelog for 9.0.0 release
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#490 Do not submit running pipelines data until accurate start time is known
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
  src/main/java/org/datadog/jenkins/plugins/datadog/traces/DatadogWebhookBuildLogic.java
Labels: changelog/Fixed

#488 Update plugin configuration docs
  README.md
Labels: changelog/no-changelog, documentation

#489 Fix freshly-cloned shared library checkout detection
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListenerTest.java
Labels: changelog/Fixed

#491 Release 9.0.1 CHANGELOG
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#492 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: changelog/Added

#464 Validate HTTP connectivity for Agent traces port
  src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogAgentClient.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/DatadogAgentConfiguration.java
Labels: changelog/Added

#447 Add a link to Datadog to job details page
  README.md
  docker/docker-compose.yaml
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/DatadogAgentConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/DatadogApiConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/DatadogClientConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/api/intake/DatadogIntakeSite.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/DatadogLinkAction.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/help-datadogAppHostnameEntry.html
  src/main/webapp/icons/dd_icon_rgb.png
  src/test/java/org/datadog/jenkins/plugins/datadog/apm/TracerInjectionIT.java
Labels: changelog/Added, documentation

#495 Add UI control and env var to configure if Datadog links are shown
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListener.java
  src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration/config.jelly
Labels: changelog/Added

#496 Ensure environment variables have higher priority than plugin configuration stored on disk
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/DatadogAgentConfiguration.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/api/intake/DatadogIntakeSite.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/api/intake/DatadogIntakeUrls.java
  src/main/java/org/datadog/jenkins/plugins/datadog/configuration/api/key/DatadogTextApiKey.java
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfigurationTest.java
Labels: changelog/Fixed

#497 Changelog for release 9.1.0
  CHANGELOG.md
Labels: changelog/no-changelog, documentation

#498 Mark deprecated config fields as transient
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java
  src/test/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfigurationSaveTest.java
Labels: changelog/Fixed

#500 Improve accuracy of detecting branch names for repos checked out in detached HEAD state
  src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
  src/main/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogSCMListener.java
  src/main/java/org/datadog/jenkins/plugins/datadog/model/GitMetadataAction.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitMetadataBuilderCallback.java
  src/main/java/org/datadog/jenkins/plugins/datadog/util/git/GitUtils.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogBuildListenerIT.java
  src/test/java/org/datadog/jenkins/plugins/datadog/listeners/DatadogGraphListenerTest.java
  src/test/java/org/datadog/jenkins/plugins/datadog/steps/DatadogOptionsTest.java
Labels: changelog/Fixed

#501 Changelog for 9.1.2
  CHANGELOG.md
Labels: changelog/no-changelog, documentation
